// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kiai from "kiai/src/Kiai.res.mjs";
import * as React from "react";
import * as Button from "./Button.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var incr = function (x) {
    return x + 1 | 0;
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "aathn.org",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Wahaha!"
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Embedded dependency test",
                      className: "text-2xl font-semibold mt-5"
                    }),
                JsxRuntime.jsx(Kiai.make, {}),
                JsxRuntime.jsx(Button.make, {
                      children: Caml_option.some("count is " + match[0].toString()),
                      onClick: (function (param) {
                          setCount(incr);
                        })
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Kiai Not a pure module */
