// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Kiai from "kiai/src/Kiai.res.mjs";
import * as React from "react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './index.css'
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(Kiai.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
